/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EmbedCodesandbox {
        "codesanboxid": string;
    }
    interface EmbedSpotify {
        "height": string;
        "spotifylink": string;
        "width": string;
    }
    interface EmbedYoutube {
        "height": string;
        "width": string;
        "youtubeid": string;
    }
}
declare global {
    interface HTMLEmbedCodesandboxElement extends Components.EmbedCodesandbox, HTMLStencilElement {
    }
    var HTMLEmbedCodesandboxElement: {
        prototype: HTMLEmbedCodesandboxElement;
        new (): HTMLEmbedCodesandboxElement;
    };
    interface HTMLEmbedSpotifyElement extends Components.EmbedSpotify, HTMLStencilElement {
    }
    var HTMLEmbedSpotifyElement: {
        prototype: HTMLEmbedSpotifyElement;
        new (): HTMLEmbedSpotifyElement;
    };
    interface HTMLEmbedYoutubeElement extends Components.EmbedYoutube, HTMLStencilElement {
    }
    var HTMLEmbedYoutubeElement: {
        prototype: HTMLEmbedYoutubeElement;
        new (): HTMLEmbedYoutubeElement;
    };
    interface HTMLElementTagNameMap {
        "embed-codesandbox": HTMLEmbedCodesandboxElement;
        "embed-spotify": HTMLEmbedSpotifyElement;
        "embed-youtube": HTMLEmbedYoutubeElement;
    }
}
declare namespace LocalJSX {
    interface EmbedCodesandbox {
        "codesanboxid"?: string;
    }
    interface EmbedSpotify {
        "height"?: string;
        "spotifylink"?: string;
        "width"?: string;
    }
    interface EmbedYoutube {
        "height"?: string;
        "width"?: string;
        "youtubeid"?: string;
    }
    interface IntrinsicElements {
        "embed-codesandbox": EmbedCodesandbox;
        "embed-spotify": EmbedSpotify;
        "embed-youtube": EmbedYoutube;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "embed-codesandbox": LocalJSX.EmbedCodesandbox & JSXBase.HTMLAttributes<HTMLEmbedCodesandboxElement>;
            "embed-spotify": LocalJSX.EmbedSpotify & JSXBase.HTMLAttributes<HTMLEmbedSpotifyElement>;
            "embed-youtube": LocalJSX.EmbedYoutube & JSXBase.HTMLAttributes<HTMLEmbedYoutubeElement>;
        }
    }
}
